"""Utilities to export formalized graphs to Neo4j Cypher scripts."""

from __future__ import annotations

from typing import Any

from src.models import ProblemGraph


def _escape_cypher_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _format_cypher_value(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return f"'{_escape_cypher_string(value)}'"
    if isinstance(value, list):
        return "[" + ", ".join(_format_cypher_value(item) for item in value) + "]"
    return f"'{_escape_cypher_string(str(value))}'"


def _relationship_type(raw_type: str) -> str:
    normalized = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in raw_type)
    return normalized.upper() or "RELATED_TO"


def export_problem_graph_to_neo4j_cypher(
    graph: ProblemGraph,
    *,
    graph_scope: str = "formalize_problem_graph",
    clear_scope: bool = False,
) -> str:
    """Return a deterministic Cypher script that materializes a ``ProblemGraph`` in Neo4j.

    The exported graph uses:
    - node labels: ``FormalizeNode`` plus each node's typed label (e.g. ``QUANTITY``)
    - relationship type: derived from ``edge.edge_type`` (upper snake case)
    - shared scope key: ``graph_scope`` to allow side-by-side graph versions
    """

    lines: list[str] = [
        "// Auto-generated by export_problem_graph_to_neo4j_cypher",
        "CREATE CONSTRAINT formalize_node_scope_id IF NOT EXISTS",
        "FOR (n:FormalizeNode) REQUIRE (n.graph_scope, n.node_id) IS UNIQUE;",
    ]

    if clear_scope:
        lines.extend(
            [
                f"MATCH (n:FormalizeNode {{graph_scope: {_format_cypher_value(graph_scope)}}})",
                "DETACH DELETE n;",
            ]
        )

    for node in sorted(graph.nodes, key=lambda item: item.node_id):
        typed_label = _relationship_type(node.node_type.value)
        lines.append(
            f"MERGE (n:FormalizeNode:{typed_label} "
            f"{{graph_scope: {_format_cypher_value(graph_scope)}, node_id: {_format_cypher_value(node.node_id)}}})"
        )

        props = {
            "node_type": node.node_type.value,
            "label": node.label,
            "value": node.value,
            "unit": node.unit,
            "quantity_id": node.quantity_id,
            "entity_id": node.entity_id,
            "target_variable": node.target_variable,
            "semantic_role": node.semantic_role.value if node.semantic_role is not None else None,
            "operation": node.operation.value if node.operation is not None else None,
            "expression": node.expression,
            "step_id": node.step_id,
            "step_index": node.step_index,
            "confidence": node.confidence,
            "provenance": node.provenance.value,
            "notes": node.notes,
        }
        set_clauses = [f"n.{key} = {_format_cypher_value(value)}" for key, value in props.items()]
        lines.append("SET " + ", ".join(set_clauses) + ";")

    for edge in sorted(graph.edges, key=lambda item: item.edge_id):
        rel_type = _relationship_type(edge.edge_type.value)
        lines.extend(
            [
                "MATCH "
                f"(src:FormalizeNode {{graph_scope: {_format_cypher_value(graph_scope)}, node_id: {_format_cypher_value(edge.source_node_id)}}}), "
                f"(dst:FormalizeNode {{graph_scope: {_format_cypher_value(graph_scope)}, node_id: {_format_cypher_value(edge.target_node_id)}}})",
                f"MERGE (src)-[r:{rel_type} {{graph_scope: {_format_cypher_value(graph_scope)}, edge_id: {_format_cypher_value(edge.edge_id)}}}]->(dst)",
                "SET "
                f"r.edge_type = {_format_cypher_value(edge.edge_type.value)}, "
                f"r.position = {_format_cypher_value(edge.position)}, "
                f"r.confidence = {_format_cypher_value(edge.confidence)}, "
                f"r.provenance = {_format_cypher_value(edge.provenance.value)}, "
                f"r.notes = {_format_cypher_value(edge.notes)};",
            ]
        )

    if graph.target_node_id is not None:
        lines.extend(
            [
                f"MATCH (target:FormalizeNode {{graph_scope: {_format_cypher_value(graph_scope)}, node_id: {_format_cypher_value(graph.target_node_id)}}})",
                f"SET target.is_target = true, target.graph_confidence = {_format_cypher_value(graph.confidence)}, "
                f"target.graph_provenance = {_format_cypher_value(graph.provenance.value)}, target.graph_notes = {_format_cypher_value(graph.notes)};",
            ]
        )

    return "\n".join(lines) + "\n"
