from pydantic import BaseModel, ConfigDict, Field, model_validator
from typing import Dict, Any, Optional, List
from enum import Enum


class ProblemRecord(BaseModel):
    """Schema for a parsed/normalized dataset record (e.g., GSM8K)."""
    id: str  # e.g., 'gsm8k_0001'
    problem: str
    gold_answer_text: str
    gold_answer_value: float
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


class NormalizedAnswer(BaseModel):
    """Schema for representing an answer value after numeric normalization."""
    is_parsed: bool
    raw_text: str
    value: Optional[float] = None

    model_config = ConfigDict(extra="forbid")

    @model_validator(mode="after")
    def validate_value_if_parsed(self):
        if self.is_parsed and self.value is None:
            raise ValueError("Numeric value must be provided if is_parsed is True")
        if not self.is_parsed and self.value is not None:
            raise ValueError("Numeric value should not be provided if is_parsed is False")
        return self


class ReferenceSolution(BaseModel):
    """Schema for the reference solution generated by the solver (e.g., Qwen)."""
    final_answer: float = Field(description="Normalized numeric final answer")
    solution_text: str = Field(description="Full textual solution/reasoning chain")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence proxy score [0.0, 1.0]")
    schema_version: str = Field(description="Version of this schema format")
    source: str = Field(description="Model/system that generated this solution")
    structured_trace: Optional[Dict[str, Any]] = Field(
        default=None, description="Optional structured reasoning trace"
    )

    model_config = ConfigDict(extra="forbid")


# ── Solver Schemas ────────────────────────────────────────────

class SolverConfig(BaseModel):
    """Configuration for the Qwen solver client."""
    model_name: str = Field(default="Qwen/Qwen2.5-Math-7B-Instruct", description="Model identifier")
    api_base: str = Field(default="http://localhost:8000/v1", description="OpenAI-compatible API base URL")
    timeout_seconds: float = Field(default=60.0, gt=0, description="Request timeout in seconds")
    max_retries: int = Field(default=3, ge=0, le=10, description="Maximum retry attempts")
    temperature: float = Field(default=0.0, ge=0.0, le=2.0, description="Sampling temperature")
    max_tokens: int = Field(default=2048, gt=0, description="Max tokens for generation")

    model_config = ConfigDict(extra="forbid")


class SolverStatus(str, Enum):
    """Status of a solver invocation."""
    SUCCESS = "success"
    API_ERROR = "api_error"
    TIMEOUT = "timeout"
    RATE_LIMITED = "rate_limited"
    MAX_RETRIES_EXCEEDED = "max_retries_exceeded"


class SolverResponse(BaseModel):
    """Response from the Qwen solver client."""
    raw_text: Optional[str] = Field(default=None, description="Raw solver output text")
    status: SolverStatus = Field(description="Outcome status of the solver call")
    model_name: str = Field(description="Model used for generation")
    latency_ms: float = Field(ge=0, description="Total latency in milliseconds")
    attempt_count: int = Field(ge=1, description="Number of attempts made")
    error_message: Optional[str] = Field(default=None, description="Error details if failed")

    model_config = ConfigDict(extra="forbid")


# ── Answer Checking Schemas ───────────────────────────────────

class Correctness(str, Enum):
    """Student answer correctness status."""
    CORRECT = "correct"
    INCORRECT = "incorrect"
    UNPARSEABLE = "unparseable"


class AnswerCheckResult(BaseModel):
    """Result of checking a student answer against the reference."""
    correctness: Correctness = Field(description="Whether the student answer is correct")
    comparison_type: str = Field(description="Type of comparison used (exact, numeric_equivalent)")
    student_value: Optional[float] = Field(default=None, description="Normalized student numeric value")
    normalization_status: str = Field(description="Whether student answer was parseable")
    reference_value: float = Field(description="The gold/reference answer value")

    model_config = ConfigDict(extra="forbid")


# ── Diagnosis Schemas ─────────────────────────────────────────

class DiagnosisLabel(str, Enum):
    """Baseline taxonomy of student error types."""
    CORRECT_ANSWER = "correct_answer"
    ARITHMETIC_ERROR = "arithmetic_error"
    QUANTITY_RELATION_ERROR = "quantity_relation_error"
    TARGET_MISUNDERSTANDING = "target_misunderstanding"
    UNPARSEABLE_ANSWER = "unparseable_answer"
    UNKNOWN_ERROR = "unknown_error"


class ErrorLocalization(str, Enum):
    """Where in the solving process the error likely occurred."""
    NONE = "none"  # correct answer
    FINAL_COMPUTATION = "final_computation"
    INTERMEDIATE_STEP = "intermediate_step"
    TARGET_SELECTION = "target_selection"
    UNKNOWN = "unknown"


class DiagnosisResult(BaseModel):
    """Structured diagnosis of a student's error."""
    label: DiagnosisLabel = Field(description="Taxonomy label for the error type")
    localization: ErrorLocalization = Field(description="Where the error occurred in the solving process")
    explanation: str = Field(description="Internal explanation for the diagnosis")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence in this diagnosis")
    fallback_used: bool = Field(default=False, description="Whether fallback to UnknownError was used")

    model_config = ConfigDict(extra="forbid")


# ── Symbolic State & Verification (Phase 2) ──────────────────

class QuantityFact(BaseModel):
    """Atomic quantity extracted from a problem statement."""
    surface_form: str = Field(description="Original tokenized number string from text")
    value: float = Field(description="Normalized numeric value")

    model_config = ConfigDict(extra="forbid")


class OperationType(str, Enum):
    """Simple operation hypotheses for Phase 2 symbolic verification."""
    ADDITIVE = "additive"
    SUBTRACTIVE = "subtractive"
    UNKNOWN = "unknown"


class SymbolicState(BaseModel):
    """Structured state extracted from problem/reference text for grounded diagnosis."""
    quantities: List[QuantityFact] = Field(default_factory=list)
    target_text: Optional[str] = Field(default=None)
    expected_operation: OperationType = Field(default=OperationType.UNKNOWN)
    builder_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    evidence_notes: List[str] = Field(default_factory=list)

    model_config = ConfigDict(extra="forbid")


class VerificationStatus(str, Enum):
    """Outcome of symbolic consistency checking."""
    VERIFIED = "verified"
    CONFLICT = "conflict"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class VerificationResult(BaseModel):
    """Verification output used as structured evidence for diagnosis/hinting."""
    status: VerificationStatus
    predicted_label: Optional[DiagnosisLabel] = Field(default=None)
    localization_hint: ErrorLocalization = Field(default=ErrorLocalization.UNKNOWN)
    evidence_flags: List[str] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    explanation: str = Field(default="")

    model_config = ConfigDict(extra="forbid")


# ── Hinting Schemas ───────────────────────────────────────────

class HintLevel(str, Enum):
    """Pedagogical levels of hints."""
    CONCEPTUAL = "conceptual"
    RELATIONAL = "relational"
    NEXT_STEP = "next_step"


class HintResult(BaseModel):
    """Structured hint generated for a student."""
    hint_level: HintLevel = Field(description="The pedagogical level of the hint")
    hint_text: str = Field(description="The actual text displayed to the student")
    generated_status: str = Field(description="Status of the generation process (e.g., success, failure)")
    diagnosis_label_used: DiagnosisLabel = Field(description="The diagnosis label that triggered this hint")
    fallback_used: bool = Field(default=False, description="Whether a fallback strategy was used")

    model_config = ConfigDict(extra="forbid")
