// Auto-generated by export_problem_graph_to_neo4j_cypher
CREATE CONSTRAINT formalize_node_scope_id IF NOT EXISTS
FOR (n:FormalizeNode) REQUIRE (n.graph_scope, n.node_id) IS UNIQUE;
MATCH (n:FormalizeNode {graph_scope: 'llm_solution_graph'})
DETACH DELETE n;
MERGE (n:FormalizeNode:INTERMEDIATE {graph_scope: 'llm_solution_graph', node_id: 'discount_per_unit'})
SET n.node_type = 'intermediate', n.label = 'discount_per_unit', n.value = null, n.unit = 'dollars', n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.93, n.provenance = 'heuristic', n.notes = [];
MERGE (n:FormalizeNode:ENTITY {graph_scope: 'llm_solution_graph', node_id: 'entity_1'})
SET n.node_type = 'entity', n.label = 'Mr. Benson', n.value = null, n.unit = null, n.quantity_id = null, n.entity_id = 'entity_1', n.target_variable = null, n.semantic_role = null, n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.95, n.provenance = 'problem_text', n.notes = [];
MERGE (n:FormalizeNode:INTERMEDIATE {graph_scope: 'llm_solution_graph', node_id: 'excess_quantity'})
SET n.node_type = 'intermediate', n.label = 'excess_quantity', n.value = null, n.unit = 'tickets', n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.94, n.provenance = 'heuristic', n.notes = [];
MERGE (n:FormalizeNode:INTERMEDIATE {graph_scope: 'llm_solution_graph', node_id: 'gross_total'})
SET n.node_type = 'intermediate', n.label = 'gross_total', n.value = null, n.unit = 'dollars', n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.94, n.provenance = 'heuristic', n.notes = [];
MERGE (n:FormalizeNode:TARGET {graph_scope: 'llm_solution_graph', node_id: 'how_much_did_mr_benson_pay_in_all'})
SET n.node_type = 'target', n.label = 'How much did Mr. Benson pay in all?', n.value = null, n.unit = 'dollars', n.quantity_id = null, n.entity_id = 'entity_1', n.target_variable = 'how_much_did_mr_benson_pay_in_all', n.semantic_role = null, n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.85, n.provenance = 'problem_text', n.notes = [];
MERGE (n:FormalizeNode:OPERATION {graph_scope: 'llm_solution_graph', node_id: 'op_step_1_excess_quantity'})
SET n.node_type = 'operation', n.label = 'Find how many units are beyond the discount threshold.', n.value = null, n.unit = null, n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = 'subtract', n.expression = 'max(quantity_2 - quantity_4, 0)', n.step_id = 'step_1_excess_quantity', n.step_index = 1, n.confidence = 0.94, n.provenance = 'heuristic', n.notes = [];
MERGE (n:FormalizeNode:OPERATION {graph_scope: 'llm_solution_graph', node_id: 'op_step_2_discount_per_unit'})
SET n.node_type = 'operation', n.label = 'Compute the discount value applied to each discounted unit.', n.value = null, n.unit = null, n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = 'percent_of', n.expression = '(quantity_3 / 100) * quantity_1', n.step_id = 'step_2_discount_per_unit', n.step_index = 2, n.confidence = 0.93, n.provenance = 'heuristic', n.notes = [];
MERGE (n:FormalizeNode:OPERATION {graph_scope: 'llm_solution_graph', node_id: 'op_step_3_total_discount'})
SET n.node_type = 'operation', n.label = 'Multiply discounted units by the discount per unit.', n.value = null, n.unit = null, n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = 'multiply', n.expression = 'excess_quantity * discount_per_unit', n.step_id = 'step_3_total_discount', n.step_index = 3, n.confidence = 0.93, n.provenance = 'heuristic', n.notes = [];
MERGE (n:FormalizeNode:OPERATION {graph_scope: 'llm_solution_graph', node_id: 'op_step_4_gross_total'})
SET n.node_type = 'operation', n.label = 'Compute the total before any discount.', n.value = null, n.unit = null, n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = 'multiply', n.expression = 'quantity_2 * quantity_1', n.step_id = 'step_4_gross_total', n.step_index = 4, n.confidence = 0.94, n.provenance = 'heuristic', n.notes = [];
MERGE (n:FormalizeNode:OPERATION {graph_scope: 'llm_solution_graph', node_id: 'op_step_5_final_total'})
SET n.node_type = 'operation', n.label = 'Subtract the total discount from the gross total.', n.value = null, n.unit = null, n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = 'subtract', n.expression = 'gross_total - total_discount', n.step_id = 'step_5_final_total', n.step_index = 5, n.confidence = 0.95, n.provenance = 'heuristic', n.notes = [];
MERGE (n:FormalizeNode:QUANTITY {graph_scope: 'llm_solution_graph', node_id: 'quantity_1'})
SET n.node_type = 'quantity', n.label = '$40.', n.value = 40.0, n.unit = 'dollars', n.quantity_id = 'quantity_1', n.entity_id = 'entity_1', n.target_variable = null, n.semantic_role = 'unit_rate', n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.95, n.provenance = 'problem_text', n.notes = ['context=A concert ticket costs $40. Mr. Benson bought 12 tickets and r'];
MERGE (n:FormalizeNode:QUANTITY {graph_scope: 'llm_solution_graph', node_id: 'quantity_2'})
SET n.node_type = 'quantity', n.label = '12', n.value = 12.0, n.unit = 'tickets', n.quantity_id = 'quantity_2', n.entity_id = 'entity_1', n.target_variable = null, n.semantic_role = 'unit_rate', n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.95, n.provenance = 'problem_text', n.notes = ['context=s $40. Mr. Benson bought 12 tickets and received a 5% discount'];
MERGE (n:FormalizeNode:QUANTITY {graph_scope: 'llm_solution_graph', node_id: 'quantity_3'})
SET n.node_type = 'quantity', n.label = '5%', n.value = 5.0, n.unit = 'percent', n.quantity_id = 'quantity_3', n.entity_id = 'entity_1', n.target_variable = null, n.semantic_role = 'percent', n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.95, n.provenance = 'problem_text', n.notes = ['context=2 tickets and received a 5% discount for every ticket bought t'];
MERGE (n:FormalizeNode:QUANTITY {graph_scope: 'llm_solution_graph', node_id: 'quantity_4'})
SET n.node_type = 'quantity', n.label = '10.', n.value = 10.0, n.unit = 'mr benson', n.quantity_id = 'quantity_4', n.entity_id = 'entity_1', n.target_variable = null, n.semantic_role = 'threshold', n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.95, n.provenance = 'problem_text', n.notes = ['context=cket bought that exceeds 10. How much did Mr. Benson pay in all'];
MERGE (n:FormalizeNode:INTERMEDIATE {graph_scope: 'llm_solution_graph', node_id: 'total_discount'})
SET n.node_type = 'intermediate', n.label = 'total_discount', n.value = null, n.unit = 'dollars', n.quantity_id = null, n.entity_id = null, n.target_variable = null, n.semantic_role = null, n.operation = null, n.expression = null, n.step_id = null, n.step_index = null, n.confidence = 0.93, n.provenance = 'heuristic', n.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'discount_per_unit'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_3_total_discount'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_discount_per_unit_to_op_step_3_total_discount_1'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 1, r.confidence = 0.93, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'entity_1'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_1'})
MERGE (src)-[r:ENTITY_HAS_QUANTITY {graph_scope: 'llm_solution_graph', edge_id: 'edge_entity_1_owns_quantity_1'}]->(dst)
SET r.edge_type = 'entity_has_quantity', r.position = null, r.confidence = 0.9, r.provenance = 'problem_text', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'entity_1'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_2'})
MERGE (src)-[r:ENTITY_HAS_QUANTITY {graph_scope: 'llm_solution_graph', edge_id: 'edge_entity_1_owns_quantity_2'}]->(dst)
SET r.edge_type = 'entity_has_quantity', r.position = null, r.confidence = 0.9, r.provenance = 'problem_text', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'entity_1'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_3'})
MERGE (src)-[r:ENTITY_HAS_QUANTITY {graph_scope: 'llm_solution_graph', edge_id: 'edge_entity_1_owns_quantity_3'}]->(dst)
SET r.edge_type = 'entity_has_quantity', r.position = null, r.confidence = 0.9, r.provenance = 'problem_text', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'entity_1'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_4'})
MERGE (src)-[r:ENTITY_HAS_QUANTITY {graph_scope: 'llm_solution_graph', edge_id: 'edge_entity_1_owns_quantity_4'}]->(dst)
SET r.edge_type = 'entity_has_quantity', r.position = null, r.confidence = 0.9, r.provenance = 'problem_text', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'excess_quantity'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_3_total_discount'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_excess_quantity_to_op_step_3_total_discount_0'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 0, r.confidence = 0.93, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'gross_total'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_5_final_total'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_gross_total_to_op_step_5_final_total_0'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 0, r.confidence = 0.95, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'how_much_did_mr_benson_pay_in_all'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'entity_1'})
MERGE (src)-[r:DESCRIBES_ENTITY {graph_scope: 'llm_solution_graph', edge_id: 'edge_how_much_did_mr_benson_pay_in_all_describes_entity_1'}]->(dst)
SET r.edge_type = 'describes_entity', r.position = null, r.confidence = 0.82, r.provenance = 'problem_text', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_1_excess_quantity'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'excess_quantity'})
MERGE (src)-[r:OUTPUT_FROM_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_op_step_1_excess_quantity_to_excess_quantity'}]->(dst)
SET r.edge_type = 'output_from_operation', r.position = null, r.confidence = 0.94, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_2_discount_per_unit'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'discount_per_unit'})
MERGE (src)-[r:OUTPUT_FROM_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_op_step_2_discount_per_unit_to_discount_per_unit'}]->(dst)
SET r.edge_type = 'output_from_operation', r.position = null, r.confidence = 0.93, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_3_total_discount'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'total_discount'})
MERGE (src)-[r:OUTPUT_FROM_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_op_step_3_total_discount_to_total_discount'}]->(dst)
SET r.edge_type = 'output_from_operation', r.position = null, r.confidence = 0.93, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_4_gross_total'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'gross_total'})
MERGE (src)-[r:OUTPUT_FROM_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_op_step_4_gross_total_to_gross_total'}]->(dst)
SET r.edge_type = 'output_from_operation', r.position = null, r.confidence = 0.94, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_5_final_total'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'how_much_did_mr_benson_pay_in_all'})
MERGE (src)-[r:OUTPUT_FROM_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_op_step_5_final_total_to_how_much_did_mr_benson_pay_in_all'}]->(dst)
SET r.edge_type = 'output_from_operation', r.position = null, r.confidence = 0.95, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_1'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_2_discount_per_unit'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_quantity_1_to_op_step_2_discount_per_unit_1'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 1, r.confidence = 0.93, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_1'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_4_gross_total'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_quantity_1_to_op_step_4_gross_total_1'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 1, r.confidence = 0.94, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_2'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_1_excess_quantity'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_quantity_2_to_op_step_1_excess_quantity_0'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 0, r.confidence = 0.94, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_2'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_4_gross_total'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_quantity_2_to_op_step_4_gross_total_0'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 0, r.confidence = 0.94, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_3'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_2_discount_per_unit'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_quantity_3_to_op_step_2_discount_per_unit_0'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 0, r.confidence = 0.93, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'quantity_4'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_1_excess_quantity'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_quantity_4_to_op_step_1_excess_quantity_1'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 1, r.confidence = 0.94, r.provenance = 'heuristic', r.notes = [];
MATCH (src:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'total_discount'}), (dst:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'op_step_5_final_total'})
MERGE (src)-[r:INPUT_TO_OPERATION {graph_scope: 'llm_solution_graph', edge_id: 'edge_total_discount_to_op_step_5_final_total_1'}]->(dst)
SET r.edge_type = 'input_to_operation', r.position = 1, r.confidence = 0.95, r.provenance = 'heuristic', r.notes = [];
MATCH (target:FormalizeNode {graph_scope: 'llm_solution_graph', node_id: 'how_much_did_mr_benson_pay_in_all'})
SET target.is_target = true, target.graph_confidence = 0.9000000000000001, target.graph_provenance = 'heuristic', target.graph_notes = ['graph_built_from_rate_relation'];
